services:
  frontend:
    build:
      context: .
      dockerfile: ./Frontend/DockerFile
      volume:
        - ./frontend/build:/usr/share/nginx/html
      espose: 
        - "80"
    container_name: frontend
    restart: always
  
  backend:
    build:
      context: .
      dockerfile: ./backend/DockerFile
    container_name: backend  # Fixed typo here
    restart: always
    ports:  # Changed 'port' to 'ports'
      - "5004:5004"
