#writing compose file to run multiple container
version: '3.8'
services:
  frontend:
    build:
      constext: ./frontend
      dockerfile: ./frontend/dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
  
  backend:
    build:
     context: .
     dockerfile: ./backend/Dockerfile
    conatiner_name: backend
    restart: always
    porst:
      - "5004:5004"