version: '3.8'
services:
  frontend:
    build:
      context: ./Frontend  # Assuming the Dockerfile is at ./Frontend/DockerFile
      dockerfile: DockerFile
    volumes:
      - ./frontend/build:/usr/share/nginx/html  # Mount the build folder to Nginx's HTML directory
    # ports:
    #   - "80:80"  # Expose port 80 to the host machine
    container_name: frontend
    restart: always
  
  backend:
    build:
      context: ./backend  # Assuming the Dockerfile is at ./backend/DockerFile
      dockerfile: DockerFile
    container_name: backend
    restart: always
    ports:
      - "5004:5004"  # Expose backend port to host machine
