services:
  frontend:
    build:
      context: .
      dockerfile: ./Frontend/DockerFile
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
  
  backend:
    build:
      context: .
      dockerfile: ./backend/DockerFile
    container_name: backend  # Fixed typo here
    restart: always
    ports:  # Changed 'port' to 'ports'
      - "5004:5004"
