name: ci/cd to ec2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.126.225.168  << 'EOF'
            cd /home/ubuntu
            rm -rf CiandCdPrac
            git clone https://github.com/Rajesh05Github/CiandCdPrac.git
            cd CiandCdPrac
            docker compose down
            docker compose build
            docker compose up -d --remove-orphans
          EOF
